<?php include dirname(__DIR__) . '\..\layouts\header.phtml'; ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/datepicker.min.js"></script>
<div class="container my-24 px-6 mx-auto">
    <form action="<?php echo WEB_ROOT ?>/addTask" method="POST">
        <div class="container p-10 mx-auto my-auto p-10 rounded">
            <table class="min-w-full table-auto border-2 border-[#ef476f] border-collapse">
                <tbody>
                    <tr>
                        <th class="p-2 text-[#118ab2] bg-[#ffd166]">Username</th>
                        <td>
                            <input type="text" name="username"
                                class="rounded border-2 border-[#118ab2] focus:outline-none focus:border-[#ef476f]"
                                value="<?php echo $this->addTask->username?>">
                        </td>
                    </tr>
                    <tr>
                        <th class="p-2 text-[#118ab2] bg-[#ffd166]">Task</th>
                        <td>
                            <input type="text" name="taskDescription" 
                                class="rounded border-2 border-[#118ab2] focus:outline-none focus:border-[#ef476f]"
                                value="<?php echo $this->addTask->taskDescription?>">
                        </td>
                    </tr>
                    <tr>
                        <th class="p-2 text-[#118ab2] bg-[#ffd166]">Status</th>
                        <td>
                            <select class="rounded border-2 border-[#118ab2] focus:outline-none focus:border-[#ef476f]"
                                name="status" id="">
                                <option value="Pending" == "pending" ? "selected" : "" ?>
                                    Pending</option>
                                <option value="Executing" == "executing" ? "selected" : "" ?>
                                    Executing</option>
                                <option value="Finished" == "finished" ? "selected" : "" ?>
                                    Finished</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th class="p-2 text-[#118ab2] bg-[#ffd166]">Starting Date</th>
                        <td>
                            <div class="relative max-w-sm">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                    <svg aria-hidden="true" class="w-5 h-5 text-[#118ab2]" fill="currentColor"
                                        viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd"
                                            d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
                                            clip-rule="evenodd"></path>
                                    </svg>
                                </div>
                                <input datepicker datepicker-format="dd/mm/yyyy" type="text" name="startingDate"
                                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                    placeholder="Select date" value="">
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th class="p-2 text-[#118ab2] bg-[#ffd166]">Finished Date</th>
                        <td>
                            <div class="relative max-w-sm">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                    <svg aria-hidden="true" class="w-5 h-5 text-[#118ab2]" fill="currentColor"
                                        viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd"
                                            d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
                                            clip-rule="evenodd"></path>
                                    </svg>
                                </div>
                                <input datepicker datepicker-format="dd/mm/yyyy" type="text" name="finishedDate"
                                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                    placeholder="Select date" value="">
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
            <button type="submit"
                class="m-5 p-1.5 rounded-full border-2 border-[#ef476f] hover:border-transparent font-bold text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166]">Submit</button>
        </div>
    </form>
</div>

<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>