<?php include dirname(__DIR__) . '\..\layouts\header.phtml'; ?>
<form action="<?php echo WEB_ROOT ?>/updateTask/<?php echo $this->viewTask->id ?>" method="POST">
    <div class="container p-10 mx-auto my-auto p-10 rounded">
        <table class="min-w-[60rem] place-content-center table-auto border-2 border-[#ef476f] border-separate">
            <tbody>
                <tr class="divide-x-2 divide-[#ef476f]">
                    <th class="w-[10rem] p-2 text-[#118ab2] bg-[#ffd166]">Username</th>
                    <td class="p-2">
                        <input type="text" name="username" value="<?php echo $this->viewTask->username; ?>"
                            class="rounded border-2 border-[#118ab2] focus:outline-none focus:border-[#ef476f]">
                    </td>
                </tr>
                <tr class="divide-x-2 divide-[#ef476f]">
                    <th class="w-[10rem] p-2 text-[#118ab2] bg-[#ffd166]">Task</th>
                    <td class="p-2">
                        <input type="text" name="taskDescription"
                            value="<?php echo $this->viewTask->taskDescription; ?>"
                            class="rounded border-2 border-[#118ab2] focus:outline-none focus:border-[#ef476f]">

                    </td>
                </tr>
                <tr class="divide-x-2 divide-[#ef476f]">
                    <th class="w-[10rem] p-2 text-[#118ab2] bg-[#ffd166]">Status</th>
                    <td>
                        <select
                            class="rounded m-1.5 border-2 border-[#118ab2] focus:outline-none focus:border-[#ef476f]"
                            name="status" id="">
                            <option value="Pending" <?php echo $this->viewTask->status == "pending" ? "selected" : "" ?>>
                                Pending</option>
                            <option value="Executing" <?php echo $this->viewTask->status == "executing" ? "selected" : "" ?>>
                                Executing</option>
                            <option value="Finished" <?php echo $this->viewTask->status == "finished" ? "selected" : "" ?>>
                                Finished</option>
                        </select>
                    </td>
                </tr>
                <tr class="divide-x-2 divide-[#ef476f]">
                    <th class="w-[10rem] p-2 text-[#118ab2] bg-[#ffd166]">Started Date</th>
                    <td class="p-2">
                        <input type="text" name="startingDate" value="<?php echo $this->viewTask->startingDate; ?>"
                            class="rounded border-2 border-[#118ab2] focus:outline-none focus:border-[#ef476f]">
                    </td>
                </tr>
                <tr class="divide-x-2 divide-[#ef476f]">
                    <th class="w-[10rem] p-2 text-[#118ab2] bg-[#ffd166]">Finished Date</th>
                    <td class="p-2">
                        <input type="text" name="finishedDate" value="<?php echo $this->viewTask->finishedDate; ?>"
                            class="rounded border-2 border-[#118ab2] focus:outline-none focus:border-[#ef476f]">
                    </td>
                </tr>
            </tbody>
        </table>

        <button type="submit"
            class="ml-30 mt-5 mb-5 p-1.5 rounded-full border-2 border-[#ef476f] hover:border-transparent font-bold text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166]">Submit
            changes</button>
        <br>
        <button type="button"
            class="ml-30 mb-5 p-1.5 rounded-full border-2 border-[#ef476f] hover:border-transparent font-bold text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166]"><a
                href="<?php echo WEB_ROOT ?>">Return to homepage</a></button>
    </div>
</form>
<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>