<?php include dirname(__DIR__) . '\..\layouts\header.phtml';?>
<form action="">
    <div>
        <div>
            <label for="">Username</label>
        </div>
        <div>
            <label for="">Task</label>
        </div>
        <div>
            <label for="">Status</label>
        </div>
        <div>
            <label for="">Started Date</label>
        </div>
        <div>
            <label for="">Finished Date</label>
        </div>
    </div>
</form>
<?php include dirname(__DIR__) . '\..\layouts\footer.phtml';?>