<?php include dirname(__DIR__) . '\..\layouts\header.phtml';?>
<div class="container p-10 mx-auto my-auto flex justify-center grid grid-rows-2 bg-slate-500 place-content-center rounded">
    <div class="container p-10 mx-auto my-auto row-span-1 bg-slate-200 place-content-center p-5">
        <a href="addTask">Add Task</a>
    </div>
    <div>
        <table class="bg-slate-300">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Task</th>
                    <th>Status</th>
                    <th>Started Date</th>
                    <th>Finished Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->listTasks as $sel_task): ?>
                <tr>
                    <td><?php echo $sel_task->username ?></td>
                    <td><?php echo $sel_task->task ?></td>
                    <td><?php echo $sel_task->status ?></td>
                    <td><?php echo $sel_task->startingDate ?></td>
                    <td><?php echo $sel_task->finishedDate ?></td>
                    <td>
                        <div><div>
                                <a href="viewTask/<?php echo $sel_task->id?>">View</a>
                            </div>
                            <div>
                                <a href="updateTask/<?php echo $sel_task->id?>">Edit</a>
                            </div>
                            <div>
                                <a href="">Delete</a>
                            </div>

                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php include dirname(__DIR__) . '\..\layouts\footer.phtml';?>

