<?php include dirname(__DIR__) . '\..\layouts\header.phtml'; ?>
<div class="ml-32 p-15">
    <button
        class="p-1.5 rounded-full border-2 border-[#ef476f] hover:border-transparent font-bold text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166]"><a
            href="addTask">Add Task</a></button>
</div>
<div class="p-10 h-auto m-10 flex justify-center grid grid-rows-2 place-content-center">
    <table class="min-w-full table-auto border-2 border-[#ef476f] border-collapse">
        <thead class="font-['Roboto'] rounded">
            <tr class="divide-x-2 divide-[#ef476f]">
                <th class="p-2 text-[#118ab2] bg-[#ffd166]">Username</th>
                <th class="p-2 text-[#118ab2] bg-[#ffd166]">Task</th>
                <th class="p-2 text-[#118ab2] bg-[#ffd166]">Status</th>
                <th class="p-2 text-[#118ab2] bg-[#ffd166]">Actions</th>
            </tr>
        </thead>
        <tbody class="text-[#06d6a0]">
            <?php foreach ($this->listTasks as $sel_task): ?>
                <tr class="divide-x-2 divide-[#ef476f]">
                    <td class="text-center p-2">
                        <?php echo $sel_task->username ?>
                    </td>
                    <td class="text-center p-2">
                        <?php echo $sel_task->taskDescription ?>
                    </td>
                    <td class="text-center p-2">
                        <?php echo $sel_task->status ?>
                    </td>
                    <td>
                        <div
                            class="container flex justify-center place-items-center grid grid-cols-2 gap-5 p-5 mx-auto my-auto">
                            <div class="col-span-1">
                                <button type="button"
                                    class="p-1.5 rounded-full border-2 border-[#ef476f] hover:border-transparent font-bold text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166]">
                                <a href="viewTask/<?php echo $sel_task->id ?>">View</a></button>
                            </div class="col-span-1">
                            <div class="col-span-1">
                                <button type="button"
                                    class="p-1.5 rounded-full border-2 border-[#ef476f] hover:border-transparent font-bold text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166]"><a
                                        href="<?php echo $this->deleteTask ?>">Delete</a></button>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="ml-32 p-15">
    <button
        class="p-1.5 rounded-full border-2 border-[#ef476f] hover:border-transparent font-bold text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166]"><a
            href="addTask">Add Task</a></button>
</div>
<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>