<?php include dirname(__DIR__) . '\..\layouts\header.phtml'; ?>

<!-- TODO: form table to input new data -->
<form action="<?php echo WEB_ROOT?>/updateTask/:id" method="POST">
    <div class="container p-10 mx-auto my-auto p-10 rounded">
        <table class="min-w-full table-auto border-2 border-[#ef476f] border-collapse">
            <tbody>
                <tr>
                    <th class="p-2 text-[#118ab2] bg-[#ffd166]">Username</th>
                    <td class="p-2">
                        <input type="text" name="username" value="<?php echo $this->updateTask->username; ?>">
                    </td>
                </tr>
                <tr>
                    <th class="p-2 text-[#118ab2] bg-[#ffd166]">Task</th>
                    <td class="p-2">
                    <input type="text" name="task" value="<?php echo $this->updateTask->task; ?>">

                    </td>
                </tr>
                <tr>
                    <th class="p-2 text-[#118ab2] bg-[#ffd166]">Status</th>
                    <td class="p-2" name="status">
                    <input type="text" name="status" value="<?php echo $this->updateTask->status; ?>">

                    </td>
                </tr>
                <tr>
                    <th class="p-2 text-[#118ab2] bg-[#ffd166]">Started Date</th>
                    <td class="p-2">
                        <input type="text" name="startingDate" value="<?php echo $this->updateTask->startingDate; ?>">
                    </td>
                </tr>
                <tr>
                    <th class="p-2 text-[#118ab2] bg-[#ffd166]">Finished Date</th>
                    <td class="p-2">
                        <input type="text" name="finishedDate" value="<?php echo $this->updateTask->finishedDate; ?>">

                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <button type="submit" class="p-10">Submit changes</button>
    <button type="button"><a href="<?php echo WEB_ROOT?>">Return to homepage</a></button>
</form>
<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>