</body>
<footer class="container p-10 mx-auto my-auto rounded">
  <section class="grid grid-cols-4">
    <div class="col-span-2 grid grid-flow-row auto-rows-max">
      <a target="_blank" href="https://goo.gl/maps/xbuwgwPv9m7PLUEj6?coh=178573&entry=tt" class="text-[#06d6a0] p-0.5"><span><i
            class="p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa fa-location-dot"></span></i>
        Roc Boronat, 117-127</a>
      <a target="_blank" href="tel:932917610" class="text-[#06d6a0] p-0.5"><span><i
            class="p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa fa-phone"></span></i>
        932 917 610</a>
        <a target="_blank" href="mailto:cibernarium@barcelonactiva.cat" class="text-[#06d6a0] p-0.5"><span><i
              class=" p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa fa-envelope"></span></i>
          cibernarium@barcelonactiva.cat</a>
    </div>
    <div class="col-span-2 flex justify-end items-end content-end">
      <a target="_blank" href="https://www.instagram.com/barcelonactiva/"><i
          class="p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa-brands fa-instagram"></i>
      <a target="_blank" href="https://twitter.com/barcelonactiva"><i
          class="p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa-brands fa-square-twitter"></i>
      <a target="_blank" href="https://www.linkedin.com/company/barcelona-activa/"><i
          class="p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa-brands fa-linkedin"></i>
      <a target="_blank" href="https://www.facebook.com/barcelonactiva/"><i
          class="p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa-brands fa-facebook"></i>
      <a target="_blank" href="https://www.youtube.com/user/videosbarcelonactiva"><i
          class="p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa-brands fa-youtube"></i>
      <a target="_blank" href="https://www.slideshare.net/barcelonactiva"><i
          class="p-1.5 m-2 w-7 text-[#06d6a0] hover:text-[#118ab2] hover:bg-[#ffd166] rounded-full fa-brands fa-slideshare"></i>
    </div>
  </section>
  <footer class="flex justify-center grid-col-4 col-span-4 text-[#06d6a0] p-4">&copy; IT Academy 2023</footer>
</footer>
</body>

</html>